### PR TITLE
Google analytics via vue-analytics init

### PR DESCRIPTION
**Pull request by nicksarafa**

### CODE REVIEW

**Comment by nicksarafa** [comment]
#229

**Comment by nicksarafa** [comment]
@JollyBrackets we might want to seperate the analytics into a seperate store/file similar to our firebase and router implementations

**Comment by JollyBrackets** [comment]
@nicksarafa I throught about doing that for Vuetify as well but it felt weird. main.js sofar is only 39 lines, so I'm ok to leave it like this.

**Review by JollyBrackets — APPROVED** [review]

**Comment by JollyBrackets** [comment]
@nicksarafa How do we access the Google Analytics dashboard?

**Comment by nicksarafa** [comment]
@JollyBrackets please DM me your email address and i'll great you view acccess to the Google analytics dashboard

**Pull request merged**
